//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace League.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supporteur_Ticket
    {
        public int SupporteurID { get; set; }
        public int TicketID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Supporteur Supporteur { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
