//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace League.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfert
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int ManagerID { get; set; }
        public int ManagerID2 { get; set; }
        public int PlayerID { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Manager Manager1 { get; set; }
        public virtual Player Player { get; set; }
    }
}
