//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fo6League.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeagueDBEntities : DbContext
    {
        public LeagueDBEntities()
            : base("name=LeagueDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad> Ads { get; set; }
        public virtual DbSet<Arbitre> Arbitres { get; set; }
        public virtual DbSet<Avertissement> Avertissements { get; set; }
        public virtual DbSet<Carton> Cartons { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<Evenement> Evenements { get; set; }
        public virtual DbSet<Formation> Formations { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<publicite> publicites { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Stadium> Stadia { get; set; }
        public virtual DbSet<Supporteur> Supporteurs { get; set; }
        public virtual DbSet<Supporteur_Ticket> Supporteur_Ticket { get; set; }
        public virtual DbSet<Suspension> Suspensions { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TempsFort> TempsForts { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<Transfert> Transferts { get; set; }
        public virtual DbSet<Type_ticket> Type_ticket { get; set; }
    }
}
