//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fo6League.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int ID { get; set; }
        public byte[] Photo { get; set; }
        public string PhotoMIME { get; set; }
        public Nullable<int> AdID { get; set; }
        public Nullable<int> publicitesID { get; set; }
        public Nullable<int> EvenementID { get; set; }
    
        public virtual Ad Ad { get; set; }
        public virtual Evenement Evenement { get; set; }
        public virtual publicite publicite { get; set; }
    }
}
