//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fo6League.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Supporteur_Ticket = new HashSet<Supporteur_Ticket>();
        }
    
        public int ID { get; set; }
        public int Quanttity { get; set; }
        public int Type_ticketID { get; set; }
        public int MatchID { get; set; }
    
        public virtual Match Match { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supporteur_Ticket> Supporteur_Ticket { get; set; }
        public virtual Type_ticket Type_ticket { get; set; }
    }
}
